# -*- coding: utf-8 -*-
"""DSI_Vis_a1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF-n3x21LmABJ_lvWOSEbeZkgABLVcNR
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests

np.random.seed(613)
x = np.arange(50)
y = np.random.randint(0, 100,50)

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y)

fig, ax = plt.subplots(figsize=(5, 3))
ax.bar(x,y)

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y)

fig, ax = plt.subplots(figsize=(5, 3))
ax.hist(y)

ax.set_title('Total growth over time')
ax.set_ylabel('Total growth')
ax.set_xlabel('Years since start')
fig.tight_layout()

font1 = {'family':'sans-serif'
,
'color':'blue'
,
'size':20}
font2 = {'family':'monospace'
,
'color':'green'
,
'size':14}

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y)
ax.set_title('Total growth over time'
, fontdict = font1)
ax.set_ylabel('Total growth'
, fontdict = font2)
ax.set_xlabel('Years since start'
, fontdict = font2)
fig.tight_layout()

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y)
ax.set_ylabel('Total growth'
, fontdict = font2)
ax.set_xlabel('Years since start'
, fontdict = font2)

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,
y,
marker='*'
, # NEW ADDITIONS
color = "indigo") # NEW ADDITIONS
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,
y,
marker='*'
,
color = 'indigo'
,
linestyle = '--'
, # NEW ADDITIONS
linewidth = 2) # NEW ADDITIONS
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
# color being the new addition
ax.plot(x,y,marker='*'
, color = '#7425b9'
, linestyle = '--'
, linewidth = 2)
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y,marker='*'
,
markersize = 12,
color = '#7425b9'
,
linestyle = '--'
,
linewidth = 2,
markeredgecolor = '#fa9359'
,
markerfacecolor = '#000000' )
ax.grid(axis = 'y'
, color = "blue"
, linewidth = 2, linestyle = '-.')
fig.show()

#Session - 2

fig, ax = plt.subplots(figsize=(5, 3))
fig.patch.set_facecolor('red')
ax.set_facecolor('green')
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y)
fig.show()

#Customzing plots

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests
np.random.seed(613)
x = np.arange(50)
y1 = np.random.randint(0, 100,50)
y2 = np.random.randint(0, 100,50)

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y1, label = "Person 1" )
ax.plot(x,y2, label = "Person 2" )
ax.legend(loc='lower right')
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y1, label = "Person 1")
ax.plot(x,y2, label = "Person 2")
ax.legend(loc='lower right',
 frameon = True, #add frame around the legend
 fontsize = 12, #change font size
 ncol = 2, #specify number of columns
 shadow = True )
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y1, label = "Person 1")
ax.plot(x,y2, label = "Person 2")
ax.legend(loc='upper left',
 bbox_to_anchor =(1, 1))
fig.show()

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')

ax.text(10, 95, "This value is important!")
fig.show()

ax.text(10, 95, "This value is important!",
 ha='center', ##alignment of text
 color = 'red', ##modify font colour
 size = 20) ##modify font size
fig.show()

fig, ax = plt.subplots()
ax.axis([0, 10, 0, 10])

ax.text(1, 5, ". Data:(1, 5)", transform=ax.transData )
ax.text(0.5, 0.1, ". Axes:(0.5, 0.1)", transform=ax.transAxes )
ax.text(0.2, 0.2, ". Figure:(0.2, 0.2)", transform=fig.transFigure )

ax.text(1, 5, ". Data: (1, 5)", transform=ax.transData )
ax.text(0.5, 0.1, ". Axes: (0.5, 0.1)", transform=ax.transAxes )
ax.text(0.2, 0.2, ". Figure: (0.2, 0.2)", transform=fig.transFigure )

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
ax.annotate('This is important!', xy=(10, 95), xytext=(20, 94),
 arrowprops=dict(facecolor='black'))
fig.show()

ax.annotate('This is important!',
 xy=(10, 95), xytext=(20, 94),
 arrowprops = dict(arrowstyle = "wedge",
 color = "hotpink"))
fig.show()
fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
ax.yaxis.set_major_locator(plt.NullLocator())
ax.xaxis.set_major_formatter(plt.NullFormatter())

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
ax.xaxis.set_major_locator(plt.MaxNLocator(3))

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))

fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
plt.xticks(rotation=45, ha='right')

font1 = {'family':'serif','color':'indigo'}
fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x,y1, label = "Person 1")
ax.scatter(x,y2, label = "Person 2")
ax.legend(loc='lower right')
plt.xlabel('Shiny New X Axis!', fontsize = 18, fontdict = font1)

plt.style.available
plt.style.use('fivethirtyeight')
np.random.seed(613)
x = np.arange(50)
y1 = np.random.randint(0, 100,50)
y2 = np.random.randint(0, 100,50)
fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x,y1)
ax.plot(x,y2)
fig.show()

#Session: Subplots and Combining

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests
np.random.seed(613)
x1 = np.arange(50)
y1 = np.random.randint(0, 75,50)
x2 = np.array(["Luffy", "Zoro", "Nami", "Usopp", "Sanji"])
y2 = np.array([110, 180, 240, 99, 220])

fig, ax = plt.subplots(figsize=(5, 3))

fig,(ax1, ax2) = plt.subplots(ncols=2,
 nrows=1,
 figsize=(7, 3))

fig, (ax1, ax2) = plt.subplots(ncols=2,
 nrows=1,
 figsize=(7, 3))
ax1.scatter(x1,y1)
ax2.bar(x2,y2)
fig.show()

fig, someaxes = plt.subplot_mosaic([['ax1', 'ax3'],
 ['ax2', 'ax3']],
 figsize=(7, 4))
someaxes["ax1"].scatter(x1,y1)
someaxes["ax2"].bar(x2,y2)
someaxes["ax3"].plot(x1,y1)
plt.show()

fig, someaxes = plt.subplot_mosaic([['ax1', 'ax3'],
 ['ax2', 'ax3']],
 figsize=(7, 4))
someaxes["ax1"].scatter(x1,y1)
someaxes["ax2"].bar(x2,y2)
someaxes["ax3"].plot(x1,y1)
someaxes["ax1"].set_xlabel('A Big Label',fontsize=18)
someaxes["ax2"].set_xlabel('Another Label',fontsize=18)
someaxes["ax3"].set_xlabel('Label 2: 2 Fast 2 Furious',fontsize=18 )

fig, someaxes = plt.subplot_mosaic([['ax1', 'ax3'],
 ['ax2', 'ax3']],
 figsize=(7, 4),
 layout = "constrained")
someaxes["ax1"].scatter(x1,y1)
someaxes["ax2"].bar(x2,y2)
someaxes["ax3"].plot(x1,y1)
someaxes["ax1"].set_xlabel('A Big Label', fontsize=18)
someaxes["ax2"].set_xlabel('Another Label', fontsize=18)
someaxes["ax3"].set_xlabel('Label 2: 2 Fast 2 Furious', fontsize=18)

# first make our sample data
x = np.array(["Luffy", "Zoro", "Nami", "Usopp", "Sanji"])
y1 = np.array([110, 180, 240, 99, 220])
y2 = np.array([170, 100, 90, 120, 50])
# define our figure and axes (just one this time)
fig, ax = plt.subplots(figsize=(7, 3))
# now call both bar and plot elements to the same axes (ax)
ax.bar(x, y1,
color = "indigo")
ax.plot(x, y2,
color = "red")

y2_sd = np.std(y2)
fig, ax = plt.subplots(figsize=(7, 3))
ax.plot(x, y2, color = "red")

ax.errorbar(x, #our x values
 y2, #our y values
 yerr = y2_sd,
 fmt = 'o')
fig.show()

fig, ax = plt.subplots(figsize=(7, 3))
ax.plot(x, y2,
 color = "red")
ax.errorbar(x,
 y2,
 yerr = y2_sd,
 fmt = "none",
 ecolor= "indigo",
 elinewidth= 4,
 capsize = 6,
 capthick= 4 )



from PIL import Image # to open images
import requests # to get images from URLs
from io import BytesIO # to store images

response = requests.get('https://placehold.co/600x400.png') # Using a publicly accessible placeholder image
print(f"Request Status Code: {response.status_code}")
print(f"Content Type: {response.headers.get('Content-Type')}")
image_file = BytesIO(response.content)
image = Image.open(image_file)

fig, ax = plt.subplots(figsize=(7, 3))
ax.plot(x, y2, color = "red")

ax_image = fig.add_axes([0.1, # x coordinate (ON FIGURE, NOT AXES)
 0.11, # y coordinate (ON FIGURE, NOT AXES)
 0.15, # image width
 0.35]) # image height

ax_image.imshow(image)
fig.show()

fig, ax = plt.subplots(figsize=(7, 3))
ax.plot(x, y2,
 color = "red")
ax_image = fig.add_axes([0.1, 0.11, 0.15, 0.35])
ax_image.imshow(image)
ax_image.axis('off')

#seaborn session

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests

tips = sns.load_dataset("tips")
print(tips)

sns.lineplot(data=tips, # choose our dataset
 x='total_bill', # define our x variable
 y='tip') # define our y variable

sns.set_style('whitegrid')

tipgraph = sns.lineplot(data=tips,
 x='total_bill',
 y='tip')
tipgraph.set(title='Tips vs. Total Bill',
 xlabel='Total Bill ($)',
 ylabel='Tip Amount ($)'



tipgraph = sns.lineplot(data=tips,
 x='total_bill',
 y='tip')
tipgraph.set(title='Tips vs. Total Bill',
 xlabel='Total Bill ($)',
 ylabel='Tip Amount ($)')

fig = plt.subplots(figsize=(10, 3))

tipgraph = sns.lineplot(data=tips,
 x='total_bill',
 y='tip',
 color = 'hotpink',
 linestyle = '--',
 linewidth = 3,
 marker = 'o',
 markerfacecolor = 'indigo')

tipgraph = sns.scatterplot(data=tips, x='total_bill',
 y='tip', style = 'time', hue =
 'day', palette = ['purple',
 'hotpink', 'deepskyblue',
 'yellowgreen'])
tipgraph.set(title='Tips vs. Total Bill',
 xlabel='Total Bill ($)',
 ylabel='Tip Amount ($)')

sns.pairplot(
 data = tips,
 hue = 'day')

daysplot = sns.relplot(
 data=tips,
 x="total_bill",
 y="tip",
 hue="sex",
 col="day",
 kind="scatter",
 col_wrap=2

#Plotly

import plotly.graph_objects as go # 'go' is 'graph objects’
x1 = np.array(["Luffy", "Zoro", "Nami", "Usopp", "Sanji"])
y1 = np.array([110, 180, 240, 99, 220])

graph = go.Figure()
graph.add_trace(go.Bar(x=x1, y=y1))

graph.update_layout(
 title="Pirate Scores",
 xaxis_title="Pirates",
 yaxis_title="Scores"
)
graph.show()

graph = go.Figure()
graph.add_trace(go.Scatter(x=x1, y=y1, mode='markers', # we want points for a scatter plot
 marker=dict(
 size=15, # point size
 color='hotpink', # point colour
 opacity=1, # point transparency/alpha
 line=dict(width=5, color='purple') # point outline
 )))
graph.update_layout(
 title='Interactive Pirate Plot',
 xaxis_title='Pirates',
 yaxis_title='Scores',
 width=500, height=500)

from wordcloud import WordCloud
df = pd.read_csv("https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/movie_quotes.csv",
on_bad_lines='skip')
df

# join all our text from each row from our quote column into a string
text = " ".join(each for each in df.quote)
# generate our wordcloud image
wordcloud = WordCloud(background_color="white",
colormap = 'inferno').generate(text)
# use matplotlib syntax to put our image in a figure
fig, ax = plt.subplots(figsize=(7, 3))
ax.imshow(wordcloud, # remember 'imshow' from when we added pictures to our matplotlib axes
 interpolation='bilinear') # this line helps smooth our image
ax.axis("off")

from matplotlib_venn import venn2, venn2_circles, venn2_unweighted

A = set(["apple", "banana", "watermelon"])
B = set(["pumpkin", "blueberry", "apple", "key lime"])

diagram = venn2_unweighted([A, B],
 set_labels = ('Fruits', 'Pies'),
 set_colors=("blue", "red"),
 alpha=0.5)
plt.show()

diagram.get_label_by_id("10")\
.set_text("n".join(A - B))
diagram.get_label_by_id("11")\
.set_text("n".join(A & B))
diagram.get_label_by_id("01")\
.set_text("n".join(B - A))

diagram = venn2_unweighted([A, B],
 set_labels = ('Fruits', 'Pies'),
 set_colors=("blue", "red"),
 alpha=0.5)
diagram.get_label_by_id("10")\
.set_text("\n".join(A - B))
diagram.get_label_by_id("11")\
.set_text("\n".join(A & B))
diagram.get_label_by_id("01")\
.set_text("\n".join(B - A))
plt.show()